#! /bin/sh
## Set up the LCD Screen under Arch
## you are going to need to be root
## JDIP 20190706
#
echo "SETTING UP THE LCD SCREEN"
## Better options 20190706
echo "options fbtft_device name=hktft9340 busnum=1 rotate=270" > /etc/modprobe.d/cloudshell.conf
echo spi_s3c64xx > /etc/modules-load.d/fbtft_device.conf
echo spidev >> /etc/modules-load.d/fbtft_device.conf
echo fbtft_device >> /etc/modules-load.d/fbtft_device.conf
echo "COMPLETE"

# Reboot
su
modprobe fbtft_device name=hktft9340 busnum=1 rotate=270
# The screen should be alive now
