#! /bin/sh
## Set up the LCD Screen under Arch
## you are going to need to be root
## JDIP 20190706
#
echo "SETTING UP THE LCD SCREEN"
## Better options 20190706
echo "options fbtft_device name=hktft9340 busnum=1 rotate=270" > /etc/modprobe.d/cloudshell.conf
echo spi_s3c64xx > /etc/modules-load.d/fbtft_device.conf
echo spidev >> /etc/modules-load.d/fbtft_device.conf
echo fbtft_device >> /etc/modules-load.d/fbtft_device.conf
echo "COMPLETE"

# Reboot
su
modprobe fbtft_device name=hktft9340 busnum=1 rotate=270
# The screen should be alive now
#
# Install NMON
git clone https://github.com/DaveBurkhardt/cloudshell-nmon
#pacman -Syu base-devel
# you need ncurses
pacman -Syu ncurses core-utils nmon
# need to manually build the thing now
sudo cp miniwi-8.psf.gz /usr/share/fonts
sudo cp cloudshell-nmon /usr/local/bin
# update the NMON environment variables
# update the cloudshell-nmon script to point to the right place
##
# Let’s create a file called /etc/systemd/system/nmon.service:
[Unit]
Description=nmon
After=network.target
StartLimitIntervalSec=0
[Service]
Type=simple
Restart=always
RestartSec=1
User=centos
ExecStart=/usr/local/bin/cloudshell-nmon
[Install]
WantedBy=multi-user.target
     
